<?php

return [
  [
    'icon'     => 'fa fa-dashboard',
    'label'    => 'Dashboard',
    'route'    => 'backend.dashboard',
    'isActive' => 'dashboard',
  ],
  [
    'icon'     => 'fa fa-bank',
    'label'    => 'Dokumen Hukum',
    'route'    => 'tes',
    'isActive' => 'dashboard/peraturan*',
    'subMenu'  => [
      [
        'icon'     => 'fa fa-pencil-square-o',
        'label'    => 'Peraturan',
        'route'    => 'backend.peraturan.index',
        'isActive' => 'dashboard/peraturan*',
      ],
      [
        'icon'     => 'fa fa-pencil-square-o',
        'label'    => 'Monografi Hukum',
        'route'    => 'tes',
        'isActive' => 'dashboard/monografi*',
      ],
      [
        'icon'     => 'fa fa-pencil-square-o',
        'label'    => 'Artikel Hukum',
        'route'    => 'tes',
        'isActive' => 'dashboard/artikel*',
      ],
      [
        'icon'     => 'fa fa-balance-scale',
        'label'    => 'Putusan',
        'route'    => 'tes',
        'isActive' => 'dashboard/putusan*',
      ],
    ],
  ],
  // [
  //   'icon'     => 'fa fa-recycle',
  //   'label'    => 'Sirkulasi',
  //   'route'    => 'tes',
  //   'isActive' => 'backend/sirkulasi*',
  //   'subMenu'  => [
  //     [
  //       'icon'     => 'fa fa-circle-o',
  //       'label'    => 'Peminjaman',
  //       'route'    => 'tes',
  //       'isActive' => 'backend/sirkulasi/peminjaman',
  //     ],
  //     [
  //       'icon'     => 'fa fa-circle-o',
  //       'label'    => 'Pengembalian',
  //       'route'    => 'tes',
  //       'isActive' => 'backend/sirkulasi/pengembalian',
  //     ],
  //     [
  //       'icon'     => 'fa fa-circle-o',
  //       'label'    => 'Sejarah Peminjaman',
  //       'route'    => 'tes',
  //       'isActive' => 'backend/sirkulasi/index',
  //     ],
  //   ],
  // ],
  [
    'icon'     => 'fa fa-image',
    'label'    => 'Berita',
    'route'    => 'backend.berita.index',
    'isActive' => 'dashboard/berita*',
  ],
  [
    'icon'     => 'fa fa-pencil-square-o',
    'label'    => 'Narasi & Quotes',
    'route'    => 'tes',
    'isActive' => 'backend/narasi*',
  ],
  [
    'icon'     => 'fa fa-pencil-square-o',
    'label'    => 'Informasi Hukum',
    'route'    => 'backend.informasi-hukum.index',
    'isActive' => 'dashboard/informasi-hukum*',
  ],
  [
    'icon'     => 'fa fa-image',
    'label'    => 'Pengumuman',
    'route'    => 'backend.pengumuman.index',
    'isActive' => 'dashboard/pengumuman*',
  ],
  [
    'icon'     => 'fa fa-video-camera',
    'label'    => 'Video',
    'route'    => 'backend.video.index',
    'isActive' => 'dashboard/video*',
  ],
  [
    'icon'     => 'fa fa-database',
    'label'    => 'Master Data',
    'route'    => 'tes',
    'isActive' => 'backend/*',
    'subMenu'  => [
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'GMD',
        'route'    => 'tes',
        'isActive' => 'backend/gmd*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Jenis Informasi Hukum',
        'route'    => 'tes',
        'isActive' => 'backend/jenis-informasi-hukum*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Jenis Pengarang',
        'route'    => 'tes',
        'isActive' => 'backend/jenis-pengarang*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Kala Terbit',
        'route'    => 'tes',
        'isActive' => 'backend/kala-terbit*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Penerbit',
        'route'    => 'tes',
        'isActive' => 'backend/penerbit*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Pengarang',
        'route'    => 'tes',
        'isActive' => 'backend/pengarang*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Pola Eksemplar',
        'route'    => 'tes',
        'isActive' => 'backend/pola-eksemplar*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Tempat Penetapan',
        'route'    => 'tes',
        'isActive' => 'backend/daerah*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Tipe Koleksi',
        'route'    => 'tes',
        'isActive' => 'backend/tipe-koleksi*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Tipe Pengarang',
        'route'    => 'tes',
        'isActive' => 'backend/tipe-pengarang*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Tipe Dokumen',
        'route'    => 'tes',
        'isActive' => 'backend/tipe-dokumen*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Tipe Kata Kunci',
        'route'    => 'tes',
        'isActive' => 'backend/tipe-kata-kunci*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Klasifikasi',
        'route'    => 'tes',
        'isActive' => 'backend/klasifikasi*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Bidang Hukum',
        'route'    => 'tes',
        'isActive' => 'backend/bidang-hukum*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Bahasa',
        'route'    => 'tes',
        'isActive' => 'backend/bahasa*',
      ],
      [
        'icon'     => 'fa fa-circle-o',
        'label'    => 'Urusan Pemerintahan',
        'route'    => 'tes',
        'isActive' => 'backend/urusan-pemerintahan*',
      ],
    ],
  ],
  [
    'icon'     => 'fa fa-unlock',
    'label'    => 'Akses Kontrol',
    'route'    => 'tes',
    'isActive' => 'backend/admin*' || 'backend/member*',
    'subMenu'  => [
      [
        'icon'     => 'fa fa-users',
        'label'    => 'User',
        'route'    => 'tes',
        'isActive' => 'backend/admin/user*',
      ],
      [
        'icon'     => 'fa fa-users',
        'label'    => 'Member',
        'route'    => 'tes',
        'isActive' => 'backend/member*',
      ],
      [
        'icon'     => 'fa fa-gears',
        'label'    => 'Route',
        'route'    => 'tes',
        'isActive' => 'backend/admin/route*',
      ],
      [
        'icon'     => 'fa fa-cog',
        'label'    => 'Role',
        'route'    => 'tes',
        'isActive' => 'backend/admin/role*',
      ],
      [
        'icon'     => 'fa fa-map',
        'label'    => 'Menu',
        'route'    => 'tes',
        'isActive' => 'backend/admin/menu*',
      ],
    ],
  ],
];
